# k8s/login-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
        - name: login-app
          image: wiyuwarwoyo/login-app:latest
          ports:
            - containerPort: 3000
